import * as THREE from 'three';
import * as C from 'cannon-es';
export function mountGame(root:HTMLElement){
const el=(id:string)=>root.querySelector<HTMLElement>('#'+id)!;
const scene=new THREE.Scene();scene.background=new THREE.Color('#e2e9e1');scene.fog=new THREE.Fog('#e2e9e1',40,115);
let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false})}catch{el('status').textContent='This browser needs WebGL enabled to play. Try Chrome or Edge.';return()=>{}}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor('#e2e9e1');el('scene').appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(43,1,.1,180);camera.position.set(15,23,29);
scene.add(new THREE.HemisphereLight(0xffffff,0x697d68,2.6));const sun=new THREE.DirectionalLight(0xfff2d9,3.3);sun.position.set(-15,35,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-40,right:40,top:40,bottom:-40,far:100});sun.shadow.bias=-.0005;scene.add(sun);scene.add(sun.target);
const world=new C.World({gravity:new C.Vec3(0,-19,0)});(world.solver as C.GSSolver).iterations=12;world.defaultContactMaterial.friction=.35;world.defaultContactMaterial.restitution=.12;
const stone=new THREE.MeshStandardMaterial({color:0xe8e8d7,roughness:.86});const edge=new THREE.MeshStandardMaterial({color:0x748775,roughness:.9});const green=new THREE.MeshStandardMaterial({color:0x597d58,roughness:.9});const gold=new THREE.MeshStandardMaterial({color:0xf2a45f,metalness:.45,roughness:.22,emissive:0xb05515,emissiveIntensity:.12});
const dynamic:{body:C.Body,mesh:THREE.Mesh}[]=[];
function box(x:number,y:number,z:number,w:number,h:number,d:number,mat=stone,mass=0){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh);const body=new C.Body({mass,shape:new C.Box(new C.Vec3(w/2,h/2,d/2)),position:new C.Vec3(x,y,z)});world.addBody(body);if(mass)dynamic.push({body,mesh});return {body,mesh}}
function platform(x:number,z:number,w:number,d:number){box(x,-.65,z,w,1.3,d);const base=new THREE.Mesh(new THREE.BoxGeometry(w-.35,.2,d-.35),edge);base.position.set(x,-1.4,z);scene.add(base)}
// A continuous course: broad decks connected by progressively narrower bridges.
platform(0,0,10,10);platform(0,-10,5,10);platform(0,-20,10,10);platform(9,-20,8,4.5);platform(18,-20,10,10);platform(18,-30,4.4,10);platform(18,-40,11,10);platform(8,-40,9,3.5);platform(-2,-40,11,11);
// Low rails protect the training stretch, with open sections later.
for(const x of [-2.55,2.55])box(x,.24,-10,.22,.48,10,edge);
for(const x of [-5,5])box(x,.3,0,.2,.6,10,edge);box(0,.3,5,10,.6,.2,edge);
for(const x of [15.75,20.25])box(x,.18,-30,.18,.36,10,edge);
// Physical obstacles: movable crates and a revolving sweeper.
for(const [x,z] of [[-2,-19],[2,-22],[16,-39],[20,-42]])box(x,.6,z,1.2,1.2,1.2,new THREE.MeshStandardMaterial({color:0xbd9774,roughness:.85}),2);
const sweeper=box(18,.65,-20,7,.35,.35,gold);sweeper.body.type=C.Body.KINEMATIC;sweeper.body.angularVelocity.set(0,.65,0);
const checkpoints=[new THREE.Vector3(0,.6,2),new THREE.Vector3(0,.6,-20),new THREE.Vector3(18,.6,-40),new THREE.Vector3(-2,.6,-40)];
const rings:THREE.Mesh[]=[];checkpoints.forEach((p,i)=>{const m=new THREE.Mesh(new THREE.TorusGeometry(i===3?1.7:1.25,.07,8,48),new THREE.MeshStandardMaterial({color:i===3?0xf5b45a:0x83b9a0,emissive:i===3?0xe9a040:0x429779,emissiveIntensity:.5}));m.rotation.x=-Math.PI/2;m.position.set(p.x,.08,p.z);scene.add(m);rings.push(m)});
// Sculptural trees and tiny gardens sit outside the driving line.
function tree(x:number,z:number,s=1){const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.12*s,.16*s,1.3*s,7),new THREE.MeshStandardMaterial({color:0x9a8263}));trunk.position.set(x,.65*s,z);trunk.castShadow=true;scene.add(trunk);for(let i=0;i<3;i++){const crown=new THREE.Mesh(new THREE.IcosahedronGeometry((1.05-i*.2)*s,0),green);crown.position.set(x,(1.7+i*.5)*s,z);crown.castShadow=true;scene.add(crown)}}
for(const [x,z,s] of [[-3.5,-3,1],[3.7,2,.7],[-3.6,-23,.85],[21,-23,1],[22,-43,.8],[-5.6,-43,1]])tree(x,z,s);
for(let i=0;i<22;i++){const angle=i*2.399;const x=9+Math.cos(angle)*(26+i%5*3),z=-18+Math.sin(angle)*(27+i%4*3);const rock=new THREE.Mesh(new THREE.IcosahedronGeometry(2+i%4,0),edge);rock.position.set(x,-10-i%5*2,z);rock.scale.y=.5;scene.add(rock);if(i%3===0){const cloud=new THREE.Mesh(new THREE.SphereGeometry(4,12,8),new THREE.MeshStandardMaterial({color:0xf2f4ec,roughness:1,transparent:true,opacity:.5}));cloud.scale.set(2,.3,1);cloud.position.set(x,-5,z);scene.add(cloud)}}
const gems=[[-1,-6],[1,-13],[-2,-21],[9,-20],[19,-24],[18,-32],[20,-39],[7,-40]].map(([x,z])=>{const mesh=new THREE.Mesh(new THREE.OctahedronGeometry(.38),gold);mesh.position.set(x,.95,z);mesh.castShadow=true;scene.add(mesh);return {mesh,x,z,collected:false}});
const marble=new THREE.Mesh(new THREE.SphereGeometry(.5,32,24),new THREE.MeshStandardMaterial({color:0xef8551,metalness:.32,roughness:.2}));marble.castShadow=true;scene.add(marble);const stripe=new THREE.Mesh(new THREE.TorusGeometry(.495,.025,8,48),new THREE.MeshStandardMaterial({color:0xffe2b5,metalness:.3,roughness:.2}));marble.add(stripe);
const ball=new C.Body({mass:1,shape:new C.Sphere(.5),position:new C.Vec3(0,.6,2),linearDamping:.28,angularDamping:.3});world.addBody(ball);
const keys=new Set<string>();let playing=false,paused=false,won=false,elapsed=0,cp=0,count=0,last=performance.now(),raf=0,toastTimer:ReturnType<typeof setTimeout>,audio:AudioContext|undefined,sound=false;
function ping(freq=620){if(!sound)return;try{audio??=new AudioContext();const osc=audio.createOscillator(),gain=audio.createGain();osc.frequency.value=freq;gain.gain.setValueAtTime(.07,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.2);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.2)}catch{}}
function toast(text:string){el('toast').textContent=text;el('toast').style.opacity='1';clearTimeout(toastTimer);toastTimer=setTimeout(()=>el('toast').style.opacity='0',2200)}
function respawn(){const p=checkpoints[cp];ball.position.set(p.x,p.y,p.z);ball.velocity.setZero();ball.angularVelocity.setZero();ball.force.setZero();ball.quaternion.set(0,0,0,1)}
function reset(){elapsed=0;cp=0;count=0;won=false;paused=false;gems.forEach(g=>{g.collected=false;g.mesh.visible=true});dynamic.forEach(({body,mesh})=>{body.position.set(mesh.userData.x??body.initPosition.x,body.initPosition.y,body.initPosition.z);body.velocity.setZero();body.angularVelocity.setZero();body.quaternion.set(0,0,0,1)});respawn();el('gems').textContent='0 / 8';el('checkpoint').textContent='01 / 04';el('pause').textContent='Ⅱ Pause'}
function play(){if(won)reset();playing=true;paused=false;el('panel').style.display='none';el('pause').textContent='Ⅱ Pause';keys.clear()}
function pause(){if(!playing||won)return;paused=!paused;keys.clear();el('panel').style.display=paused?'block':'none';el('panel-title').textContent='Take a breath.';el('status').textContent='Your marble is right where you left it.';el('play').innerHTML='Keep rolling <span>↗</span>';el('pause').textContent=paused?'▶ Resume':'Ⅱ Pause'}
el('play').onclick=play;el('pause').onclick=pause;el('restart').onclick=()=>{reset();play();toast('Fresh start. You’ve got this.')};el('sound').onclick=()=>{sound=!sound;el('sound').textContent=sound?'Sound on':'Sound off';ping()};
const down=(e:KeyboardEvent)=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='KeyR'&&playing){respawn();toast('Back to your checkpoint')}if(e.code==='Escape'||e.code==='KeyP')pause();if(e.code==='Enter'&&!playing)play()};const up=(e:KeyboardEvent)=>keys.delete(e.code);const blur=()=>{keys.clear();if(playing&&!paused&&!won)pause()};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);const visibility=()=>{if(document.hidden)blur()};document.addEventListener('visibilitychange',visibility);
root.querySelectorAll<HTMLElement>('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key!)};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.key!)});
const lifecycle=new AbortController();
const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;
if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'restart_game',description:'Restart the marble course from the beginning and begin playing.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');reset();play();return {status:'playing',checkpoint:1,gems:0}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}
const size=()=>{renderer.setSize(root.clientWidth,root.clientHeight);camera.aspect=root.clientWidth/root.clientHeight;camera.updateProjectionMatrix()};size();window.addEventListener('resize',size);
const target=new THREE.Vector3(),desired=new THREE.Vector3();let intro=true;
function tick(now:number){raf=requestAnimationFrame(tick);const dt=Math.min((now-last)/1000,.05);last=now;if(playing&&!paused&&!won){elapsed+=dt;let x=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft')),z=Number(keys.has('KeyS')||keys.has('ArrowDown'))-Number(keys.has('KeyW')||keys.has('ArrowUp'));const n=Math.hypot(x,z);if(n){x/=n;z/=n;ball.applyForce(new C.Vec3(x*15,0,z*15))}if(keys.has('Space')){ball.velocity.x*=Math.exp(-7*dt);ball.velocity.z*=Math.exp(-7*dt);ball.angularVelocity.scale(Math.exp(-7*dt),ball.angularVelocity)}const speed=Math.hypot(ball.velocity.x,ball.velocity.z);if(speed>6){ball.velocity.x*=6/speed;ball.velocity.z*=6/speed}world.step(1/60,dt,4);if(ball.position.y<-7){respawn();toast('Clouds caught you. Back to your checkpoint.');ping(230)}for(const g of gems){g.mesh.rotation.y+=dt;g.mesh.position.y=.9+Math.sin(now*.002+g.x)*.14;if(!g.collected&&Math.hypot(ball.position.x-g.x,ball.position.z-g.z)<1&&ball.position.y>.1){g.collected=true;g.mesh.visible=false;count++;el('gems').textContent=count+' / 8';ping(580+count*65)}}for(let i=cp+1;i<checkpoints.length;i++){if(Math.hypot(ball.position.x-checkpoints[i].x,ball.position.z-checkpoints[i].z)<1.5&&ball.position.y>.1){cp=i;el('checkpoint').textContent='0'+(cp+1)+' / 04';if(i<3){toast('Checkpoint saved ✦');ping(900)}else{won=true;el('panel').style.display='block';el('panel-title').textContent='Beautifully done.';el('status').textContent=`You crossed the clouds in ${elapsed.toFixed(1)} seconds and collected ${count} of 8 gems.`;el('play').innerHTML='Roll again <span>↗</span>';try{const best=Number(localStorage.getItem('orbit-best'))||Infinity;if(elapsed<best)localStorage.setItem('orbit-best',String(elapsed));el('best').textContent='Personal best · '+Math.min(best,elapsed).toFixed(1)+' seconds'}catch{}ping(1200)}}}el('time').textContent=String(Math.floor(elapsed/60)).padStart(2,'0')+':'+(elapsed%60).toFixed(1).padStart(4,'0')}
marble.position.copy(ball.position as unknown as THREE.Vector3);marble.quaternion.copy(ball.quaternion as unknown as THREE.Quaternion);for(const o of dynamic){o.mesh.position.copy(o.body.position as unknown as THREE.Vector3);o.mesh.quaternion.copy(o.body.quaternion as unknown as THREE.Quaternion)}sweeper.mesh.quaternion.copy(sweeper.body.quaternion as unknown as THREE.Quaternion);
if(!playing){target.set(6,0,-16);desired.set(27,34,28)}else{target.set(ball.position.x,0,ball.position.z-3);desired.set(ball.position.x+3,19,ball.position.z+19)}if(intro){camera.position.copy(desired);intro=false}else camera.position.lerp(desired,1-Math.exp(-3*dt));camera.lookAt(target);sun.position.set(ball.position.x-15,35,ball.position.z+12);sun.target.position.set(ball.position.x,0,ball.position.z);renderer.render(scene,camera)}tick(performance.now());
return()=>{lifecycle.abort();cancelAnimationFrame(raf);clearTimeout(toastTimer);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);window.removeEventListener('resize',size);document.removeEventListener('visibilitychange',visibility);scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.dispose())}});renderer.dispose();renderer.domElement.remove();audio?.close()}
}
