import * as T from 'three';
import {track,trackLength,TRACK_POINTS,ROAD_HALF,TOTAL_LAPS,pointAt,createCars,stepCar,botInput,resolveCars,recover,positionOf,nearest,type Car} from './simulation';
export function mountRace(root:HTMLElement){
 const $=(id:string)=>root.querySelector<HTMLElement>('#'+id)!;
 const scene=new T.Scene();scene.background=new T.Color('#d3ae89');scene.fog=new T.Fog('#d3ae89',115,310);
 let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'})}catch{$('race-description').textContent='Enable WebGL in your browser to play. Try Chrome or Edge.';return()=>{}}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;$('race-canvas').appendChild(renderer.domElement);
 const camera=new T.PerspectiveCamera(58,1,.1,450);scene.add(new T.HemisphereLight(0xffe6c1,0x77634e,2.6));const sun=new T.DirectionalLight(0xffd19a,3.6);sun.position.set(-55,75,-35);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-70,right:70,top:70,bottom:-70,near:1,far:200});sun.shadow.bias=-.0007;scene.add(sun);scene.add(sun.target);
 const material=(color:number,roughness=.85)=>new T.MeshStandardMaterial({color,roughness});const sand=material(0xcba677),asphalt=material(0x484b45),dark=material(0x252b28),white=material(0xeee1c8),red=material(0xc95131),metal=material(0x737d75,.5),glass=material(0x253f40,.25);
 const ground=new T.Mesh(new T.PlaneGeometry(900,900),sand);ground.rotation.x=-Math.PI/2;ground.position.y=-.08;ground.receiveShadow=true;scene.add(ground);
 function box(w:number,h:number,d:number,mat:T.Material,x=0,y=0,z=0,parent:T.Object3D=scene){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 function strip(inner:number,outer:number,height:number,mat:T.Material,colored=false){const positions:number[]=[],colors:number[]=[];for(let i=0;i<TRACK_POINTS;i++){const a=pointAt(track[i].s,inner),b=pointAt(track[i].s,outer),c=pointAt(track[i+1].s,inner),d=pointAt(track[i+1].s,outer);const color=new T.Color(Math.floor(i/4)%2?0xe9d6b8:0xc65739);for(const p of [a,b,c,b,d,c]){positions.push(p.x,height,p.z);colors.push(color.r,color.g,color.b)}}const geom=new T.BufferGeometry();geom.setAttribute('position',new T.Float32BufferAttribute(positions,3));if(colored)geom.setAttribute('color',new T.Float32BufferAttribute(colors,3));geom.computeVertexNormals();const mesh=new T.Mesh(geom,mat);mesh.receiveShadow=true;scene.add(mesh)}
 asphalt.side=T.DoubleSide;strip(-ROAD_HALF,ROAD_HALF,.02,asphalt);const curbMat=new T.MeshStandardMaterial({vertexColors:true,side:T.DoubleSide,roughness:.9});strip(-ROAD_HALF-.7,-ROAD_HALF,.04,curbMat,true);strip(ROAD_HALF,ROAD_HALF+.7,.04,curbMat,true);const lineMat=material(0xe1d7b9);lineMat.side=T.DoubleSide;strip(-ROAD_HALF+.25,-ROAD_HALF+.4,.045,lineMat);strip(ROAD_HALF-.4,ROAD_HALF-.25,.045,lineMat);
 // Dashed center guide and low, continuous roadside barriers.
 for(let s=8;s<trackLength;s+=9){const p=pointAt(s);const line=box(.12,.015,2.4,white,p.x,.04,p.z);line.rotation.y=Math.atan2(p.tx,p.tz)}
 const barrierGeo=new T.BoxGeometry(.5,.85,3.8);for(const side of [-1,1]){const n=Math.ceil(trackLength/3.7),inst=new T.InstancedMesh(barrierGeo,white,n);inst.castShadow=true;inst.receiveShadow=true;const dummy=new T.Object3D();for(let i=0;i<n;i++){const p=pointAt(i*trackLength/n,side*(ROAD_HALF+1.8));dummy.position.set(p.x,.42,p.z);dummy.rotation.y=Math.atan2(p.tx,p.tz);dummy.updateMatrix();inst.setMatrixAt(i,dummy.matrix);inst.setColorAt(i,new T.Color(Math.floor(i/3)%2?0xebe0c8:0xd76a42))}scene.add(inst)}
 // The starting line and trackside gantry are visible from the grid.
 for(let i=0;i<12;i++)for(let j=0;j<2;j++){const p=pointAt(j*.7,(i-5.5)*1.35);const tile=box(1.35,.03,.7,(i+j)%2?white:dark,p.x,.075,p.z);tile.rotation.y=0}
 const gate=new T.Group();const gridPoint=pointAt(0);gate.position.set(gridPoint.x,0,gridPoint.z);scene.add(gate);box(.35,7,.35,metal,-11,3.5,0,gate);box(.35,7,.35,metal,11,3.5,0,gate);box(22.4,1.4,.6,dark,0,7,0,gate);
 function textTexture(text:string,bg='#252b28',fg='#fff0d9'){const c=document.createElement('canvas');c.width=1024;c.height=128;const ctx=c.getContext('2d')!;ctx.fillStyle=bg;ctx.fillRect(0,0,1024,128);ctx.fillStyle=fg;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 58px Arial';ctx.fillText(text,512,67);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;return tex}
 const signMat=new T.MeshBasicMaterial({map:textTexture('D U S T R U N    /    START — FINISH'),side:T.DoubleSide});const sign=new T.Mesh(new T.PlaneGeometry(20,1.1),signMat);sign.position.set(0,7,-.32);gate.add(sign);
 const lightMeshes:T.Mesh[]=[];for(let i=0;i<3;i++){const l=new T.Mesh(new T.SphereGeometry(.2,10,8),new T.MeshStandardMaterial({color:0x6d3329,emissive:0xff3a13,emissiveIntensity:.2}));l.position.set((i-1)*1.2,5.8,-.1);gate.add(l);lightMeshes.push(l)}
 // Grandstand, pit tents, desert vegetation, and distant mesas.
 const stand=new T.Group();stand.position.set(108,0,-10);stand.rotation.y=Math.PI/2;scene.add(stand);for(let i=0;i<5;i++){box(23,.7,2,material(i%2?0xc85e3b:0xdac09c),0,.4+i*.65,i*1.8,stand)}box(25,.25,11,dark,0,6,3,stand);for(const x of [-11,11])for(const z of [-1,7])box(.2,6,.2,metal,x,3,z,stand);
 for(let i=0;i<22;i++){const spectator=new T.Mesh(new T.IcosahedronGeometry(.3,0),material([0x405761,0xdea753,0xa85638,0xe3d6b9][i%4]));spectator.position.set(99+(i%5)*1.5,1.9+Math.floor(i/5)*.65,-19+(i%7)*2.8);scene.add(spectator)}
 for(let i=0;i<3;i++){const p=pointAt(34+i*17,17);const tent=new T.Group();tent.position.set(p.x,0,p.z);tent.rotation.y=Math.atan2(p.tx,p.tz);scene.add(tent);box(7,.18,7,i%2?white:red,0,3.8,0,tent);for(const x of [-3,3])for(const z of [-3,3])box(.1,3.8,.1,metal,x,1.9,z,tent);box(3,1,1.5,dark,0,.5,1,tent)}
 const cactusMat=material(0x6d7952);function cactus(x:number,z:number,h:number){const trunk=new T.Mesh(new T.CylinderGeometry(.24,.32,h,7),cactusMat);trunk.position.set(x,h/2,z);trunk.castShadow=true;scene.add(trunk);for(const side of [-1,1]){box(.8,.28,.28,cactusMat,x+side*.45,h*.55,z);box(.25,h*.36,.25,cactusMat,x+side*.8,h*.68,z)}}
 for(let i=0;i<45;i++){const a=i*2.399,r=25+(i*17%100),x=Math.cos(a)*r,z=Math.sin(a)*r;if(nearest(x,z).distance>16)cactus(x,z,2+(i%4)*.65)}
 const rockMat=material(0xb78e69);for(let i=0;i<38;i++){const a=i*.97,r=105+(i%6)*14;const mesh=new T.Mesh(new T.CylinderGeometry(6+i%5,12+i%8,9+i%7*2,5),rockMat);mesh.position.set(Math.cos(a)*r,2,Math.sin(a)*r);mesh.rotation.y=a;mesh.castShadow=true;scene.add(mesh)}
 // Car models use a shared simple silhouette, with visible tires and racing stripes.
 function makeCar(color:number){const g=new T.Group(),paint=material(color,.35);box(1.9,.5,3.75,paint,0,.58,0,g);box(1.8,.16,1.2,paint,0,.84,1.12,g);const cabin=box(1.45,.53,1.6,glass,0,1.08,-.25,g);cabin.rotation.x=-.05;box(1.45,.1,1.1,paint,0,1.38,-.3,g);box(.21,.015,1.25,white,-.2,.93,1.1,g);box(.21,.015,1.25,white,.2,.93,1.1,g);box(1.9,.12,.3,dark,0,.97,-1.7,g);box(.15,.35,.12,dark,-.65,.85,-1.7,g);box(.15,.35,.12,dark,.65,.85,-1.7,g);box(1.65,.16,.14,dark,0,.39,1.94,g);for(const x of [-.62,.62]){box(.4,.12,.035,white,x,.68,1.89,g);box(.4,.1,.035,red,x,.66,-1.89,g)}const wheels:T.Mesh[]=[];for(const x of [-.99,.99])for(const z of [-1.15,1.15]){const wheel=new T.Mesh(new T.CylinderGeometry(.39,.39,.26,14),dark);wheel.rotation.z=Math.PI/2;wheel.position.set(x,.4,z);wheel.castShadow=true;g.add(wheel);wheels.push(wheel);const hub=new T.Mesh(new T.CylinderGeometry(.21,.21,.28,10),metal);hub.rotation.z=Math.PI/2;hub.position.copy(wheel.position);g.add(hub)}scene.add(g);return {g,wheels}}
 let cars=createCars();const models=cars.map(c=>makeCar(c.color));
 const map=$('minimap') as HTMLCanvasElement,mapctx=map.getContext('2d')!;
 function drawMap(){const c=mapctx;c.clearRect(0,0,240,180);const xy=(x:number,z:number)=>[120+x*1.03,90+z*1.03];c.beginPath();track.forEach((p,i)=>{const [x,y]=xy(p.x,p.z);if(i)c.lineTo(x,y);else c.moveTo(x,y)});c.closePath();c.lineWidth=10;c.strokeStyle='#fff3da27';c.stroke();c.lineWidth=1;c.strokeStyle='#fff0d78a';c.stroke();for(let i=cars.length-1;i>=0;i--){const car=cars[i],[x,y]=xy(car.x,car.z);c.beginPath();c.arc(x,y,i?3.5:5,0,Math.PI*2);c.fillStyle='#'+car.color.toString(16).padStart(6,'0');c.fill();if(!i){c.lineWidth=1.5;c.strokeStyle='#fff7df';c.stroke()}}}
 const keys=new Set<string>(),touch=new Set<string>();let state:'ready'|'countdown'|'racing'|'paused'|'finished'='ready',beforePause:'countdown'|'racing'='racing',countdown=3.8,elapsed=0,raf=0,last=performance.now(),accumulator=0,noticeTimer:ReturnType<typeof setTimeout>,sound=false,audio:AudioContext|undefined,engine:OscillatorNode|undefined,gain:GainNode|undefined,lastLap=1;
 function notify(t:string){$('race-notice').textContent=t;$('race-notice').style.opacity='1';clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('race-notice').style.opacity='0',2200)}
 function audioOn(){try{audio??=new AudioContext();audio.resume();if(!engine){engine=audio.createOscillator();engine.type='sawtooth';gain=audio.createGain();gain.gain.value=0;engine.connect(gain);gain.connect(audio.destination);engine.start()}}catch{}}
 function start(){if(state==='paused'){state=beforePause;$('race-panel').style.display='none';$('race-pause').textContent='Ⅱ';return}cars=createCars();state='countdown';countdown=3.8;elapsed=0;accumulator=0;lastLap=1;keys.clear();touch.clear();$('race-panel').style.display='none';$('race-pause').textContent='Ⅱ';$('race-countdown').textContent='3';if(sound)audioOn();notify('Beat the bots. Brake before the corners.')}
 function pause(){if(state==='ready'||state==='finished')return;if(state==='paused'){start();return}beforePause=state;state='paused';keys.clear();touch.clear();$('race-panel').style.display='block';$('race-title').innerHTML='Pit stop.';$('race-description').textContent='Race paused. Ready when you are.';$('race-start').innerHTML='Back to the race <span>↗</span>';$('race-pause').textContent='▶';$('race-countdown').textContent=''}
 function finish(){state='finished';const position=positionOf(cars[0],cars);$('race-panel').style.display='block';$('race-title').innerHTML=position===1?'Own the<br/><em>sunset.</em>':'Across the<br/><em>finish line.</em>';$('race-description').textContent=`You finished ${['','1st','2nd','3rd','4th'][position]} of 4 in ${formatTime(elapsed)}. ${position===1?'The checkered flag is yours.':'Try braking early and accelerating out of corners.'}`;$('race-start').innerHTML='Race again <span>↗</span>';try{const prior=Number(localStorage.getItem('dustrun-best'))||Infinity;if(elapsed<prior)localStorage.setItem('dustrun-best',String(elapsed));$('race-best').textContent='Personal best · '+formatTime(Math.min(prior,elapsed))}catch{}notify(position===1?'WINNER · YOU':'RACE COMPLETE')}
 function formatTime(t:number){return String(Math.floor(t/60)).padStart(2,'0')+':'+(t%60).toFixed(2).padStart(5,'0')}
 $('race-start').onclick=start;$('race-restart').onclick=start;$('race-pause').onclick=pause;$('race-sound').onclick=()=>{sound=!sound;$('race-sound').textContent=sound?'Sound on':'Sound off';if(sound)audioOn()};
 const keydown=(e:KeyboardEvent)=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='Enter'&&(state==='ready'||state==='finished'))start();if(e.code==='Escape'||e.code==='KeyP')pause();if(e.code==='KeyR'&&state==='racing'){recover(cars[0]);notify('Back on track')}};
 const keyup=(e:KeyboardEvent)=>keys.delete(e.code),blur=()=>{keys.clear();touch.clear();if(state==='countdown'||state==='racing')pause()},visibility=()=>{if(document.hidden)blur()};window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);
 root.querySelectorAll<HTMLElement>('[data-drive]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touch.add(b.dataset.drive!)};b.onpointerup=b.onpointercancel=()=>touch.delete(b.dataset.drive!)});
 const resize=()=>{renderer.setSize(root.clientWidth,root.clientHeight);camera.aspect=root.clientWidth/root.clientHeight;camera.updateProjectionMatrix()};resize();window.addEventListener('resize',resize);
 const desired=new T.Vector3(),look=new T.Vector3(),smoothLook=new T.Vector3();let cameraInit=false,frame=0;
 function step(dt:number){if(state==='countdown'){countdown-=dt;$('race-countdown').textContent=countdown>1?String(Math.ceil(countdown-1)):'GO';lightMeshes.forEach((l,i)=>{const m=l.material as T.MeshStandardMaterial;m.emissive.set(countdown<=1?0x79ed70:0xff3a13);m.emissiveIntensity=countdown<3.8-i?1.7:.2});if(countdown<=0){state='racing';$('race-countdown').textContent=''}}else if(state==='racing'){elapsed+=dt;const gas=keys.has('KeyW')||keys.has('ArrowUp')||touch.has('gas'),brake=keys.has('KeyS')||keys.has('ArrowDown')||keys.has('Space')||touch.has('brake');const steer=Number(keys.has('KeyA')||keys.has('ArrowLeft')||touch.has('left'))-Number(keys.has('KeyD')||keys.has('ArrowRight')||touch.has('right'));stepCar(cars[0],{throttle:gas?1:0,steer,brake},dt,elapsed);for(let i=1;i<cars.length;i++)stepCar(cars[i],botInput(cars[i],i),dt,elapsed);resolveCars(cars);const lap=Math.min(TOTAL_LAPS,Math.max(1,Math.floor(cars[0].progress/trackLength)+1));if(lap>lastLap){lastLap=lap;notify(lap===3?'FINAL LAP · Make it count':'LAP '+lap+' · Keep pushing')}
 if(cars[0].finished)finish();}
 }
 function tick(now:number){raf=requestAnimationFrame(tick);const dt=Math.min(.05,(now-last)/1000);last=now;accumulator+=dt;while(accumulator>=1/60){step(1/60);accumulator-=1/60}const player=cars[0];cars.forEach((c,i)=>{const {g,wheels}=models[i];g.position.set(c.x,0,c.z);g.rotation.y=c.heading;g.rotation.z=-c.steer*Math.min(c.speed,25)*.0015;wheels.forEach(w=>{w.rotation.x+=c.speed*dt/.39})});const forward=new T.Vector3(Math.sin(player.heading),0,Math.cos(player.heading));if(state==='ready'){desired.set(player.x-14,10.5,player.z-15);look.set(player.x,1,player.z+4)}else{desired.copy(models[0].g.position).addScaledVector(forward,-9.5-Math.abs(player.speed)*.035);desired.y=5.5;look.copy(models[0].g.position).addScaledVector(forward,9);look.y=1.4}if(!cameraInit){camera.position.copy(desired);smoothLook.copy(look);cameraInit=true}camera.position.lerp(desired,1-Math.exp(-dt*5));smoothLook.lerp(look,1-Math.exp(-dt*8));camera.lookAt(smoothLook);const targetFov=58+Math.abs(player.speed)*.2;camera.fov+=(targetFov-camera.fov)*dt*3;camera.updateProjectionMatrix();sun.position.set(player.x-55,75,player.z-35);sun.target.position.set(player.x,0,player.z);
 $('race-position').innerHTML=positionOf(player,cars)+'<small> / 4</small>';$('race-lap').innerHTML=Math.min(3,Math.max(1,Math.floor(player.progress/trackLength)+1))+' <small>/ 3</small>';$('race-time').textContent=formatTime(elapsed);$('race-speed').textContent=String(Math.round(Math.abs(player.speed)*5));$('gear').textContent=player.speed<1?'N':String(Math.min(5,1+Math.floor(player.speed/7)));$('speed-bars').style.setProperty('--speed',(Math.abs(player.speed)/34*100)+'%');if(++frame%3===0)drawMap();if(engine&&gain&&audio){engine.frequency.setTargetAtTime(35+Math.abs(player.speed)*3.3,audio.currentTime,.08);gain.gain.setTargetAtTime(sound&&state==='racing'?.026:0,audio.currentTime,.08)}renderer.render(scene,camera)}
 const lifecycle=new AbortController();const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>unknown}}).modelContext;function register(name:string,description:string,readOnlyHint:boolean,execute:()=>unknown){try{Promise.resolve(context?.registerTool({name,description,inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');return execute()}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}
 register('start_race','Start or restart the three-lap race against three bots.',false,()=>{start();return {state,drivers:4,laps:3}});register('read_race','Read the race state, player position, lap, speed and elapsed time.',true,()=>({state,position:positionOf(cars[0],cars),lap:Math.min(3,Math.max(1,Math.floor(cars[0].progress/trackLength)+1)),speed:Math.round(cars[0].speed*5),elapsed}));
 tick(performance.now());return()=>{lifecycle.abort();cancelAnimationFrame(raf);clearTimeout(noticeTimer);window.removeEventListener('resize',resize);window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material]){if(m.map)m.map.dispose();m.dispose()}}});renderer.dispose();renderer.domElement.remove();audio?.close()}
}
